### ISSUE TITLE
跟着“AI初学者：使用预置算法构建模型”做，报“运行失败”，查看日志ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gracefangcs** [huaweicloud/ModelArts-Lab#1722]
跟着“AI初学者：使用预置算法构建模型”做，报“运行失败”，查看日志ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

在stderr.log里看到
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/trainjob-flowers.log
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/trainjob-flowers.log
[ModelArts Service Log]modelarts-pipe: will write log file /tmp/log/trainjob-flowers.log
[ModelArts Service Log]modelarts-pipe: param for max log length: 1073741824
[ModelArts Service Log]modelarts-pipe: param for whether exit on overflow: 0
[ModelArts Service Log]modelarts-pipe: total length: 1809

在stdout.log看到

Traceback (most recent call last):
  File "builtin_algorithms/train_wrapper.py", line 25, in <module>
    from moxing.tensorflow.builtin_algorithms.training_config import (
  File "/home/code/moxing/build/moxing/tensorflow/__init__.py", line 22, in <module>
    
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/work/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 2323 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
