### ISSUE TITLE
发布服务后的参数类型错误

### ISSUE THREAD

**Issue by liweigu** [huaweicloud/ModelArts-Lab#216]
一个简单的TensorFlow模型（代码为附件的dense.py），本地保存模型后，测试在本地加载模型（loadModelDense.py）可以正常运行。但是发布服务后，在访问服务时报错：AbortionError(code=StatusCode.INVALID_ARGUMENT, details="Expects arg[0] to be float but double is provided")（日志.png）
即使把测试数据写死（customize_service.py），打印显示类型也是float，但错误还是提示传了double。
注意：dense.py的代码拷入在线训练环境时，把 useMox = 0 改成 useMox = 1 。

环境说明：
训练用的Notebook环境是：TF-1.8.0-python2.7
安装了 pandas 0.22.0 （config.json）

[参数类型错误.zip](https://github.com/huaweicloud/ModelArts-Lab/files/3354910/default.zip)

**Comment by liweigu** [comment]
<img width="709" alt="日志" src="https://user-images.githubusercontent.com/31612697/60591115-51a46f00-9dd0-11e9-9c9e-94139f27f9be.png">

**Comment by liweigu** [comment]
将 dtype='float' 改成 dtype='float32' 后，不会报double的错误了。

**Comment by liweigu** [comment]
之后遇到的一个新问题：TypeError: Expected binary or unicode string, got (5.0, 6.0)
说明：
我在本地加载模型后，设置参数时用 df = pd.DataFrame({"a":[float(5.0)], "b":[float(6.0)]}, dtype='float')
但 def _preprocess(self, data) 返回的df不同，参数必须是"input"。
我先在 def _preprocess(self, data) 设置 df = pd.DataFrame({"input":[float(5.0),float(6.0)]}, dtype='float32') ，错误提示input[0]需要是matrix。
然后我设置 
inputData = np.array([float(5.0),float(6.0)]).astype(float)
df = pd.DataFrame({"input":[inputData]}, dtype='float32')
[customize_service.py.txt](https://github.com/huaweicloud/ModelArts-Lab/files/3358932/customize_service.py.txt)

这时会报错，日志为：
2019-07-04 10:05:48 UTC [MainThread ] - /home/mind/model_def/model_def.py[line:40] - INFO: model inputs: {u'input': tf.float32}
2019-07-04 10:06:41 UTC [MainThread ] - /home/mind/app.py[line:90] - ERROR: Algorithm crashed!
2019-07-04 10:06:41 UTC [MainThread ] - /home/mind/app.py[line:91] - ERROR: Traceback (most recent call last):
File "/home/mind/app.py", line 81, in inference_task
File "/home/mind/model_service/model_service.py", line 94, in inference
data = self._inference(data)
(bytes_or_text,))
TypeError: Expected binary or unicode string, got (5.0, 6.0)
请问该怎么解决？

**Comment by liweigu** [comment]
用pandas的话，没办法识别参数类型。
要这样设置参数：
inputData = {"input": [[float(5.0),float(6.0)]]}
return inputData

感谢官方提供的支持！
